"use strict";

var _ = require('dry-underscore');
var fstats = require('./');
var join = _.path.join;
var eq = _.test.eq;
var ok = _.test.ok;
var throws = _.test.throws;

var data = _.path.fun(_.path.normalize(__dirname + "/zandbox"));

suite('fstats');

/*
function setup_test_dir(){
    var one_kb = [];

    _.f(1024, function(){
        one_kb.push("A");
    });

    var one_kb_str = one_kb.join("");

    _.f(10, function(i){
        _.fs.write_file.sync(data("one_kb_" + i + ".txt"), one_kb_str);
    });

    _.fs.mkdir.sync(data("child"));

    _.f(10, function(i){
        _.fs.write_file.sync(data("child", "one_kb_" + i + ".txt"), one_kb_str);
    });
}

setup_test_dir();

test('count_size', function(callback){

    var fs = fstats(data());

    await{ fs.compute(_.plumb(defer(var stats), callback)); }

    _.p(stats);

    callback();
});
*/
